

orientation_display.c
190 lines

txt


drone_controller.py
589 lines

py

C:\Users\suman\OneDrive\Documents\webots_projects\ │ ├── controllers\ │   └── drone_controller\ │       ├── drone_controller.py        # Controller script for Mavic 2 PRO (with ML model integration) │       ├── orientation_model.pkl      # ML model file for predicting orientation errors │       └── scaler.pkl                 # Scaler file for preprocessing ML model inputs │ ├── plugins\ │   └── robot_windows\ │       └── orientation_display\ │           ├── orientation_display.c  # Source code for the RobotWindow plugin │           ├── orientation_display.dll # Compiled plugin (generated by Makefile) │           └── Makefile               # Makefile to compile the plugin │ └── worlds\     └── mavic_2_pro.wbt                # World file for the simulation (contains Mavic 2 PRO robot node) this is the file structure i am having and the codes are as below makefile has the code as the below  # Makefile for Webots robot_window plugin  # Webots installation directory (adjust if needed) WEBOTS_HOME ?= C:/Program Files/Webots  # Include and library paths INCLUDE = -I"$(WEBOTS_HOME)/include" LIB = -L"$(WEBOTS_HOME)/lib/controller" -lcontroller  # Compiler settings CC = gcc CFLAGS = -Wall -O2 $(INCLUDE) -DWEBOTS_ROBOT_WINDOW LDFLAGS = $(LIB) -shared  # Source and output files SOURCES = orientation_display.c TARGET = orientation_display.dll  # Default target all: $(TARGET)  # Build the DLL $(TARGET): $(SOURCES)     @echo "Building robot window plugin..."     $(CC) $(CFLAGS) $(LDFLAGS) -o $@ $^     @echo "✓ Plugin built successfully: $(TARGET)"  # Clean target clean:     @echo "Cleaning build files..."     rm -f $(TARGET)     @echo "✓ Clean completed"  # Install target (copy to Webots plugins directory) install: $(TARGET)     @echo "Installing plugin to Webots..."     copy "$(TARGET)" "$(WEBOTS_HOME)\projects\plugins\robot_windows\"     @echo "✓ Plugin installed"  # Help target help:     @echo "Available targets:"     @echo "  all     - Build the plugin (default)"     @echo "  clean   - Remove build files"     @echo "  install - Copy plugin to Webots directory"     @echo "  help    - Show this help"  .PHONY: all clean install help and what i need u to do is debug and the causes of the error i am not getting any output pop but the drone is flying stable or can we make a html ui and display it there tell me that later i will ask the codes
do one thing give the prompt to grok as how to fix and what are the errors such that i will fix it

Edit


Looking at your code structure and the files, I can identify several issues that are preventing the robot window from displaying properly. Let me create a comprehensive prompt for Grok to help you debug this:


Webots Robot Window Debug Prompt for Grok
Document 
Quick Analysis of Your Issues:
Based on your code, here are the main problems I can identify:

🔴 Critical Issues:
Missing Communication: Your Python controller never sends data to the robot window plugin. The C code expects to receive data via wb_robot_window_receive(), but your Python code has no wb_robot_window_send() calls.
World File Configuration: Your robot node in the .wbt file likely doesn't have the window field set to point to your plugin.
Plugin Installation: The DLL might not be in the correct location for Webots to find it.
🟡 Likely Fixes Needed:
Add to Python controller:
python
# Add this in your main loop
data_string = f"{roll},{pitch},{yaw},{ml_roll_error},{ml_pitch_error},{ml_yaw_error},{sim_time}"
robot.wbr_robot_window_send(data_string)
Update world file: Add window "orientation_display" to your robot node.
Fix plugin path: Ensure the DLL is in the right Webots plugins directory.
🟢 Alternative HTML Solution:
If you want to skip the robot window complexity, I can help you create a modern HTML-based dashboard that runs in a separate browser window and displays your drone data in real-time. This would be much easier to implement and debug.

Would you like me to:

Help you fix the robot window plugin issues step by step?
Create an HTML-based dashboard solution instead?
The HTML solution would be more reliable and easier to customize with modern web technologies.





Continue

orientation_display.c
6.33 KB •190 lines
Formatting may be inconsistent from source
#include <webots/robot.h>
#include <webots/robot_window.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <math.h>

#define WINDOW_WIDTH 500
#define WINDOW_HEIGHT 400
#define PI 3.14159265359

static char html_content[4096];
static double roll = 0.0, pitch = 0.0, yaw = 0.0;
static double roll_error = 0.0, pitch_error = 0.0, yaw_error = 0.0;
static double sim_time = 0.0;
static int initialized = 0;
static int update_counter = 0;

void generate_html() {
    // Convert radians to degrees
    double roll_deg = roll * 180.0 / PI;
    double pitch_deg = pitch * 180.0 / PI;
    double yaw_deg = yaw * 180.0 / PI;
    
    const char* ml_status = (roll_error != 0.0 || pitch_error != 0.0 || yaw_error != 0.0) ? "Active" : "Waiting...";
    
    snprintf(html_content, sizeof(html_content),
        "<!DOCTYPE html>"
        "<html><head>"
        "<title>Drone ML Predictions</title>"
        "<style>"
        "body { "
            "font-family: 'Courier New', monospace; "
            "background: linear-gradient(135deg, #1e1e1e, #2d2d2d); "
            "color: #ffffff; "
            "margin: 0; "
            "padding: 20px; "
        "}"
        ".container { "
            "max-width: 450px; "
            "margin: 0 auto; "
        "}"
        ".title { "
            "color: #00ff00; "
            "font-size: 18px; "
            "font-weight: bold; "
            "margin-bottom: 20px; "
            "text-align: center; "
            "text-shadow: 0 0 10px #00ff00; "
        "}"
        ".section { "
            "border: 2px solid #444; "
            "padding: 15px; "
            "margin: 10px 0; "
            "border-radius: 10px; "
            "background: rgba(0,0,0,0.3); "
            "box-shadow: 0 4px 8px rgba(0,0,0,0.5); "
        "}"
        ".section h3 { "
            "color: #ffaa00; "
            "margin-top: 0; "
            "margin-bottom: 10px; "
            "font-size: 16px; "
        "}"
        ".data-row { "
            "margin: 8px 0; "
            "font-size: 14px; "
            "padding: 5px; "
            "border-radius: 5px; "
        "}"
        ".error { "
            "color: #ff6666; "
            "background: rgba(255, 102, 102, 0.1); "
        "}"
        ".angle { "
            "color: #66ffff; "
            "background: rgba(102, 255, 255, 0.1); "
        "}"
        ".status { "
            "color: #00cc00; "
            "background: rgba(0, 204, 0, 0.1); "
        "}"
        ".progress-bar { "
            "width: 100%%; "
            "height: 20px; "
            "background: #333; "
            "border-radius: 10px; "
            "overflow: hidden; "
            "margin: 5px 0; "
        "}"
        ".progress-fill { "
            "height: 100%%; "
            "background: linear-gradient(90deg, #00ff00, #ffff00, #ff0000); "
            "transition: width 0.3s ease; "
        "}"
        "</style>"
        "<script>"
        "setTimeout(function(){ location.reload(); }, 500);"  // Auto-refresh every 0.5 seconds
        "</script>"
        "</head><body>"
        "<div class='container'>"
        "<div class='title'>🚁 DRONE ORIENTATION ML PREDICTIONS</div>"
        
        "<div class='section'>"
        "<h3>📐 Current Orientation</h3>"
        "<div class='data-row angle'>Roll: %.2f°</div>"
        "<div class='progress-bar'><div class='progress-fill' style='width: %.1f%%;'></div></div>"
        "<div class='data-row angle'>Pitch: %.2f°</div>"
        "<div class='progress-bar'><div class='progress-fill' style='width: %.1f%%;'></div></div>"
        "<div class='data-row angle'>Yaw: %.2f°</div>"
        "</div>"
        
        "<div class='section'>"
        "<h3>🤖 ML Predicted Errors</h3>"
        "<div class='data-row error'>Roll Error: %.4f</div>"
        "<div class='data-row error'>Pitch Error: %.4f</div>"
        "<div class='data-row error'>Yaw Error: %.4f</div>"
        "</div>"
        
        "<div class='section'>"
        "<h3>📊 Status</h3>"
        "<div class='data-row status'>Time: %.1f seconds</div>"
        "<div class='data-row status'>ML Status: %s</div>"
        "<div class='data-row status'>Updates: %d</div>"
        "</div>"
        
        "</div></body></html>",
        
        // Current orientation values
        roll_deg, fabs(roll_deg * 2.0),  // Roll and progress bar
        pitch_deg, fabs(pitch_deg * 2.0), // Pitch and progress bar
        yaw_deg,
        
        // ML predictions
        roll_error, pitch_error, yaw_error,
        
        // Status
        sim_time, ml_status, update_counter
    );
}

// This function is called when the robot window is created
void wb_robot_window_init() {
    printf("Robot window initializing...\n");
    
    // Set window title
    wb_robot_window_set_title("🚁 Drone ML Predictions");
    
    // Generate initial HTML
    generate_html();
    
    // Set initial content
    wb_robot_window_set_content(html_content);
    
    initialized = 1;
    printf("✓ Robot window initialized successfully\n");
}

// This function is called periodically (every simulation step)
void wb_robot_window_step(int time_step) {
    update_counter++;
    
    // Update every 10 steps to reduce CPU load
    if (update_counter % 10 == 0) {
        // Try to receive data from controller
        const char *message = wb_robot_window_receive();
        
        if (message != NULL && strlen(message) > 0) {
            // Parse the message format: "roll,pitch,yaw,roll_error,pitch_error,yaw_error,time"
            if (sscanf(message, "%lf,%lf,%lf,%lf,%lf,%lf,%lf", 
                      &roll, &pitch, &yaw, &roll_error, &pitch_error, &yaw_error, &sim_time) == 7) {
                
                // Generate and update HTML content
                generate_html();
                wb_robot_window_set_content(html_content);
                
                // Optional: Print debug info
                if (update_counter % 100 == 0) {
                    printf("Updated: Roll=%.2f°, Pitch=%.2f°, ML_Roll_Error=%.4f\n", 
                           roll * 180.0 / PI, pitch * 180.0 / PI, roll_error);
                }
            }
        }
    }
}

// This function is called when the robot window is closed
void wb_robot_window_cleanup() {
    printf("Robot window cleanup\n");
}
Claude